'use strict';var firebaseConfig={apiKey:"AIzaSyBdDxwmuS9w0VnfYzLL2ptYBI4GYUWuZqQ",authDomain:"git-hub-test-34e5a.firebaseapp.com",databaseURL:"https://git-hub-test-34e5a-default-rtdb.firebaseio.com",projectId:"git-hub-test-34e5a",storageBucket:"git-hub-test-34e5a",messagingSenderId:"824616741271",appId:"1:824616741271:web:7d068b5de85ba781757cd2",measurementId:"G-TV39YCR646"};firebase.initializeApp(firebaseConfig);var firestore=firebase.firestore();
window.fbAsyncInit=function(){FB.init({appId:"880835337346722",cookie:!0,xfbml:!0,version:"v21.0"});FB.getLoginStatus(function(a){statusChangeCallback(a)})};(function(a,b,d){var c=a.getElementsByTagName(b)[0];a.getElementById(d)||(a=a.createElement(b),a.id=d,a.src="https://connect.facebook.net/en_US/sdk.js",c.parentNode.insertBefore(a,c))})(document,"script","facebook-jssdk");let currentUserId="";
function statusChangeCallback(a){var b=document.getElementById("shapes");"connected"===a.status?(document.getElementById("fb-login-btn").style.display="none",document.getElementById("fb-logout-btn").style.display="inline",document.getElementById("survey-container").style.display="block",b.style.display="block",generateShapes(),FB.api("/me",{fields:"id,name,picture,hometown,gender,likes,link"},function(d){document.getElementById("user-name").textContent="Welcome, "+d.name+"!";document.getElementById("profile-pic").src=
d.picture.data.url;document.getElementById("delete-account-btn").style.display="inline";currentUserId=d.id;document.getElementById("profile-pic").onclick=function(c){c.stopPropagation();c=d.id;const e=d.name,f=d.hometown?d.hometown.name:"N/A",g=d.gender,h=d.likes?d.likes.data.join(", "):"None",k=d.link;c=`profile.html?id=${c}&name=${encodeURIComponent(e)}&hometown=${encodeURIComponent(f)}&gender=${g}&likes=${encodeURIComponent(h)}&link=${k}`;window.location.href=c};saveUserData(d)})):(document.getElementById("fb-login-btn").style.display=
"inline",document.getElementById("fb-logout-btn").style.display="none",document.getElementById("profile-pic").src="img/looking-good.gif",document.getElementById("user-name").textContent="Welcome!",document.getElementById("survey-container").style.display="none",b.style.display="none",document.getElementById("delete-account-btn").style.display="none")}
function saveUserData(a){var b=(new Date).toLocaleString("en-US",{weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"numeric",minute:"numeric",hour12:!0});firestore.collection("users").doc(a.id).set({name:a.name,picture:a.picture.data.url,lastLogin:b,hometown:a.hometown?a.hometown.name:"N/A",gender:a.gender,link:a.link}).then(()=>{displayLastLogin(b)}).catch(function(d){console.error("Error saving user data: ",d)})}
function displayLastLogin(a){var b=document.getElementById("last-login");b.textContent="Your last login was on "+a;b.style.display="block"}function checkLoginState(){FB.getLoginStatus(function(a){statusChangeCallback(a)})}document.getElementById("fb-login-btn").onclick=function(){FB.login(function(a){a.authResponse?statusChangeCallback(a):console.log("User cancelled login or failed.")},{scope:"public_profile,email,user_hometown,user_gender,user_link"})};
document.getElementById("fb-logout-btn").onclick=function(){FB.logout(function(a){statusChangeCallback(a);document.getElementById("profile-pic").src="img/looking-good.gif";document.getElementById("user-name").textContent="Welcome!";document.getElementById("last-login").style.display="none";document.getElementById("survey-container").style.display="none"})};
document.getElementById("survey-form").onsubmit=function(a){a.preventDefault();a=document.getElementById("question1").value;const b=document.getElementById("question2").value;a=`Favorite Color: ${a}<br>Facebook Usage: ${b}`;document.getElementById("result-text").innerHTML=a;document.getElementById("survey-results").style.display="block"};
document.getElementById("share-results").onclick=function(){var a=document.getElementById("result-text").innerHTML;a=new Blob([a],{type:"text/html"});a=URL.createObjectURL(a);const b=document.createElement("a");b.href=a;b.download="survey_results.html";document.body.appendChild(b);b.click();document.body.removeChild(b)};document.getElementById("delete-account-btn").onclick=function(){currentUserId?deleteUserData(currentUserId):console.error("No user is currently logged in.")};
function deleteUserData(a){firestore.collection("users").doc(a).delete().then(()=>{console.log("User data deleted successfully")}).catch(b=>{console.error("Error deleting user data: ",b)})}
function generateShapes(){const a=document.getElementById("shapes");a.innerHTML="";const b=["#FF4500","#00BFFF","#8A2BE2","#FF69B4"];for(let d=0;42>d;d++){const c=document.createElement("div");c.style.width=50*Math.random()+20+"px";c.style.height=c.style.width;c.style.backgroundColor="transparent";c.style.borderColor=b[Math.floor(Math.random()*b.length)];c.style.borderWidth="2px";c.style.borderStyle="solid";c.style.borderRadius=.5>Math.random()?"50%":"0";c.style.position="absolute";c.style.left=100*
Math.random()+"vw";c.style.top=100*Math.random()+"vh";a.appendChild(c)}};function hello(a){alert("Hello, "+a)}hello("New user");
